apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
type: Opaque
data:
  # property-like keys; each key maps to a simple value
  SPRING_DATASOURCE_PASSWORD: bXktYXBwLXBhc3N3b3Jk
  SPRING_DATASOURCE_USERNAME: bXktYXBw